apiVersion: v1
kind: Secret
metadata:
  name: eo-app-packaging-assistant-secret
  namespace: eo-app-packaging-assistant
data:
  .dockerconfigjson: {{ .Values.docker.configjson }}
type: kubernetes.io/dockerconfigjson