apiVersion: v1
kind: Service
metadata:
  name: eo-app-packaging-assistant
  namespace: {{ .Values.namespace }}
  labels:
    app: eo-app-packaging-assistant
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: eo-app-packaging-assistant