apiVersion: v1
kind: Service
metadata:
  name: app-import-tool
  namespace: {{ .Values.namespace }}
  labels:
    app: app-import-tool
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: app-import-tool