docker:
    configjson: ENC[AES256_GCM,data:Bzlmp53C6upPIzNw2msjMvDjU4TXjIxn1d7dTT1UxL2OKf1PkYCuzCd18AmhJSgsFa6UxLqkZCGWPI1q1VBZVwe87JHHBy5KFb3xHaIipzVlbSPxTLbyANUy5ZY+0CzIz0iaIqZA3KbpYSXnujYFSL4Usd1dysS+VSTYuyJdEXf6UEIEbV4bVMaZjCOz2s38/qTTO/QlAgrzKusj5+rZpW/xigNOAjO3t/WpLg==,iv:wK4Usdo2o3e9EntFLIrL+y/zdNYObZGJRa7/xqdOp9E=,tag:6N0zFyB+/bIWo5o6Q/g5wg==,type:str]
registry:
    password: ENC[AES256_GCM,data:NNmyXhmP9FzQkb7v,iv:v9Bd38kmRdQYbqFQkmpUwvIpu1Wnmi+izYy0DXAQuyY=,tag:TH89hQ+0c47fx2N5OknYqw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-03-15T10:10:35Z"
    mac: ENC[AES256_GCM,data:SVsF0FXT4Xj7p5CpgCvoZQYt8QIhsXu6E+5tsY1lmWe0pwDjToNx1dXe/3Uo/FhoUJPmtwDbotJgMLmE3y0iKzKZNEQiOlizXR8T++RH/PeBMq/p9K24WuqOt/8hk3qo6rT69bpkkeEE06EJC2lgn0UCJMFjs9EqaNfZAehLnl8=,iv:rfqS1vzQ/vF3OBXTEd7VbqkfCCWflqRhT2+TKL7imNk=,tag:eAKlV0Ck7ylYYCJhvTGKXA==,type:str]
    pgp:
        - created_at: "2024-03-15T10:10:35Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAw/JGNGjfQGVAQ/+PYm85sOBsJeYz0SVceLv5OvCYO27OfkF0D9hPYU6OMeK
            ZjFDk+4BJithIhhorBYEV+uAguFUZmcn76w398ToHv6elBgHvOHHKDxIy8WdzQCJ
            OE6xJA9vBXVm7SoTaVVdCA1UoUJ+1XkkoxnY0I9DKf5JslzMtNwROV69IYyx4lEb
            ItfKzn/CI7PlBeQ/CyOuTpW1Jllk3sOSVCza1BkmJDDWGTifZsIXF4+NjBZFkFcW
            rBztAsYtumzUmqo8pXByUwu9/Z9u+Uyba7CQxS+28f/SC137MX1WoFdhvSYQdrgJ
            biFABcEv1NhrYuJb5WNBdAFRAOpy5qPxbqAzaUYju3XcU90pIf6aS1/49YwDXMfF
            sNos5/0fbDTIkKYhjJhgt5GSHEk1JX/bo7gnh+wz1WPJB7/+927zIhkJBOh6GgMZ
            69iOtaW+xod+1O4eYJa8n2CZH0N49Sc0FhQYUoilKA2j3BjiciQ7A7fCbQD0O9gK
            icMZlaGNE8Y6tztYmXG1NNGFZCOJeQbvI/m2eo5479CskQbsEIig2+bB6s7q7R7m
            kQxYw4jp9QfcMMhiEg2gg6YX+EycMq+FOaP4rNx52fq2ThnpqSNzfRtPbC0K6w2m
            fD5IfIjyB7K5J0sXSt9YOg7qmPoLczL2Zl9/I4LL1q8c6IXZZE4VT5VuN8r1VFbS
            XgHs1MtdDqdklhBpc0ZYJ6M9e0aO9XA3ZrR0fCeZsIIKzjxuP5TcmZdltXYW1XMZ
            bOFf80jjl1yRh6WMQH6O0pRijJZyewJloFJT3hRinabc8kdHZFaAAaVBUNlRjC4=
            =zmnd
            -----END PGP MESSAGE-----
          fp: 8CE238DD1BCD4D31D8729E0E5182D26046FB374D
    unencrypted_suffix: _unencrypted
    version: 3.7.1
